return {
	options = {
		opt = { scrolloff = 8 },
	},

	icons = {
		ActiveLSP = "",
		ActiveTS = "",
		ArrowLeft = "",
		ArrowRight = "",
		BufferClose = "󰅖",
		DapBreakpoint = "",
		DapBreakpointCondition = "",
		DapBreakpointRejected = "",
		DapLogPoint = ".>",
		DapStopped = "󰁕",
		DefaultFile = "󰈙",
		Diagnostic = "󰒡",
		DiagnosticError = "",
		DiagnosticHint = "󰌵",
		DiagnosticInfo = "󰋼",
		DiagnosticWarn = "",
		Ellipsis = "…",
		FileModified = "",
		FileReadOnly = "",
		FoldClosed = "",
		FoldOpened = "",
		FoldSeparator = " ",
		FolderClosed = "",
		FolderEmpty = "",
		FolderOpen = "",
		Git = "󰊢",
		GitAdd = "",
		GitBranch = "",
		GitChange = "",
		GitConflict = "",
		GitDelete = "",
		GitIgnored = "◌",
		GitRenamed = "➜",
		GitStaged = "✓",
		GitUnstaged = "✗",
		GitUntracked = "★",
		LSPLoaded = "",
		LSPLoading1 = "",
		LSPLoading2 = "󰀚",
		LSPLoading3 = "",
		MacroRecording = "",
		Paste = "󰅌",
		Search = "",
		Selected = "❯",
		Spellcheck = "󰓆",
		TabClose = "󰅙",
	},

	mappings = {
		n = {
			["}<Space>"] = { "o<Esc>k", desc = "Add empty line below" },
			["{<Space>"] = { "O<Esc>j", desc = "Add empty line above" },
			["<leader>a"] = { "ggVG", desc = "Switch to visual mode and select all" },
			["gpt"] = { "<cmd>ChatGPT<cr>", desc = "Open ChatGPT client window" },
		},
		i = {
			["kj"] = { "<Esc><cmd>wa<cr>", desc = "Exit insert mode and write all changed files" },
		},
	},

	plugins = {
		{
			"AstroNvim/astrocommunity",
			{ import = "astrocommunity.pack.typescript-all-in-one" },
			{ import = "astrocommunity.pack.json" },
			{ import = "astrocommunity.pack.toml" },
			{ import = "astrocommunity.pack.yaml" },
			{ import = "astrocommunity.pack.rust" },
			{ import = "astrocommunity.pack.svelte" },
			{ import = "astrocommunity.pack.html-css" },
			{ import = "astrocommunity.pack.markdown" },
			{ import = "astrocommunity.pack.tailwindcss" },
			{ import = "astrocommunity.pack.bash" },
			{ import = "astrocommunity.pack.lua" },
			{ import = "astrocommunity.pack.python" },
			{ import = "astrocommunity.pack.java" },
			{ import = "astrocommunity.pack.kotlin" },
			{ import = "astrocommunity.motion.nvim-surround" },
			{ import = "astrocommunity.markdown-and-latex.markdown-preview-nvim" },
			{ import = "astrocommunity.editing-support.todo-comments-nvim" },
			{ import = "astrocommunity.editing-support.chatgpt-nvim" },
			{ import = "astrocommunity.editing-support.refactoring-nvim" },
			{ import = "astrocommunity.editing-support.zen-mode-nvim" },
			{ import = "astrocommunity.bars-and-lines.heirline-vscode-winbar" },
			{ import = "astrocommunity.completion.copilot-lua-cmp" },
			{ import = "astrocommunity.note-taking.obsidian-nvim" },
			{ import = "astrocommunity.color.twilight-nvim" },
		},
	},

	colorscheme = "kanagawa",
}
